# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5f98d05aaf28767c06680d9ccaacd50d2a275df99f0ec8b957087ec08c9d30b5dee796ab8a98d0cd77cbb62f2c3834a786b4190de8ac9581e4eb3832db564ad
  facebook_app_id: 1922424551375764
  facebook_app_secret: a1d31f2797cedc66c9ed7c07d9fe72b7
  twitter_app_id: s1WP9zUEpdgC8iNHSBodIwQZ6
  twitter_app_secret: rQ6LfuI3ZKjTAlkmoS8Ho4Wty8QSOOkGlDWZEPJIWOeecvChyw

test:
  secret_key_base: 86dd8aa10598104e3e58f002b2f38d79f2bc1ff6d43afd5a49f5e3dcd369ce1a8e083759e76c0f9fbc31524670022faba2393be73907afd993c9d1eb583ca1a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FB_APP_ID"] %>
  facebook_app_secret: <%= ENV["FB_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>